// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:calendar_appointment_app/appointment.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AppointmentAdapter());
    registerAdapter(RecurrenceTypeAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AppointmentAdapter());
    registerAdapter(RecurrenceTypeAdapter());
  }
}
